services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Europe/Lisbon
      - DISABLE_JEMALLOC=true    
    volumes:
      - /home/bmpinto/homeassistant:/config
      - /var/run/dbus:/var/run/dbus
    privileged: true
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyAMA0:/dev/ttyAMA0
    restart: unless-stopped
